# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: AWS

steps:
- task: ECRPushImage@1
  inputs:
    regionName: 'us-west-2'
    imageSource: 'imagename'
    sourceImageName: 'ginatells-ui'
    repositoryName: ${DOCKER_REPOSITORY_NAME}
