trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: AWS
  - name: DOCKER_REPOSITORY
    value: 'ginatells-ui'

stages:
- stage: Build
  jobs:
    - job: Build
      steps:
      - script: echo Building!
      - task: Docker@2
        displayName: Build image
        inputs:
          repository: $(DOCKER_REPOSITORY)
          command: build
          Dockerfile: Dockerfile
          tags: |
            latest
      - task: ECRPushImage@1
        displayName: Push image to ECR
        inputs:
          awsCredentials: 'AWS'
          regionName: 'us-west-2'
          imageSource: 'imagename'
          sourceImageName: $(DOCKER_REPOSITORY)
          repositoryName: $(DOCKER_REPOSITORY)
          autoCreateRepository: true
- stage: Test
  jobs:
    - job: UnitTests
      displayName: Unit Tests
      steps:
      - script: echo Unit Testing!
    - job: UITests
      displayName: UI Tests
      steps:
      - script: echo UI Testing!
- stage: Deploy
  jobs:
    - job: Deploy
      steps:
      - script: echo Deploying the code!
      