FROM node:17-alpine AS ui-build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install && npm run build

FROM node:17-alpine AS server-build
WORKDIR /root/
COPY --from=ui-build /usr/src/app/build ./ginatells-ui/build
COPY server/package*.json ./server/
RUN cd server && npm install
COPY server/ ./server/

EXPOSE 3000

CMD ["node", "./server/index.js"]
