# docker build -t ginatells-ui -f Dockerfile.production
# docker run --rm -p 3000:3000 ginatells-ui

FROM node:17-alpine AS ui-build
WORKDIR /usr/src/app
COPY . ./
RUN npm install && npm run build

FROM node:17-alpine AS server-build
WORKDIR /root/
COPY --from=ui-build /usr/src/app/build ./build
COPY server/package*.json ./server/
RUN cd server && npm install
COPY server/ ./server/

EXPOSE 3000

CMD ["node", "./server/index.js"]
